### ISSUE TITLE
createReducer cannot be called when handling more than 2 actions

### ISSUE THREAD

**Issue by zaytsevfuu** [piotrwitek/typesafe-actions#145]
## Description
Invoking a reducer which was created with more than 2 chained handleAction() calls does not compile.

## Steps to Reproduce
Following produces a ts compile error:

```
import {ActionType, createReducer, createStandardAction} from "typesafe-actions";

export type State = {
    foo: string,
};

const defaultState: State = {
    foo: "",
};

const actions = {
    foo1: createStandardAction("foo1")(),
    foo2: createStandardAction("foo2")(),
    foo3: createStandardAction("foo3")(),
    foo4: createStandardAction("foo4")(),
};

type FooActionsType = ActionType<typeof actions>;

declare module "typesafe-actions" {
    export type RootAction = FooActionsType;
}

const reducer = createReducer(defaultState)
    .handleAction(actions.foo1, (state) => {
        return {
            ...state,
        };
    })
    .handleAction(actions.foo2, (state) => {
        return {
            ...state,
        };
    })
    .handleAction(actions.foo3, (state) => {
        return {
            ...state,
        };
    })
    .handleAction(actions.foo4, (state) => {
        return {
            ...state,
        };
    });

reducer(defaultState, actions.foo1()); // error
reducer(defaultState, actions.foo2()); // error
reducer(defaultState, actions.foo3()); // ok
reducer(defaultState, actions.foo4()); // ok
```

Running tsc:

```
reducer.ts:46:23 - error TS2345: Argument of type 'EmptyAction<"foo1">' is not assignable to parameter of type 'EmptyAction<"foo3"> | EmptyAction<"foo4">'.
  Type 'EmptyAction<"foo1">' is not assignable to type 'EmptyAction<"foo3">'.
    Type '"foo1"' is not assignable to type '"foo3"'.

46 reducer(defaultState, actions.foo1()); // error
                         ~~~~~~~~~~~~~~

reducer.ts:47:23 - error TS2345: Argument of type 'EmptyAction<"foo2">' is not assignable to parameter of type 'EmptyAction<"foo3"> | EmptyAction<"foo4">'.
  Type 'EmptyAction<"foo2">' is not assignable to type 'EmptyAction<"foo3">'.
    Type '"foo2"' is not assignable to type '"foo3"'.

47 reducer(defaultState, actions.foo2()); // error
                         ~~~~~~~~~~~~~~


Found 2 errors.
```

If i remove 2 handleAction calls from the reducer, it compiles.

## Project Dependencies
```
{
  "dependencies": {
    "typesafe-actions": "4.1.1"
  },
  "devDependencies": {
    "typescript": "3.4.4"
  }
}
```

- tsconfig.json:
```
{
  "compilerOptions": {
    "strict": true,
    "noEmit": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

## Environment (optional)
- OS: macOS 10.14.2
- Node Version: v11.14.0
- Package Manager and Version: yarn v1.15.2

<img width="1313" alt="Screenshot 2019-04-26 21 50 08" src="https://user-images.githubusercontent.com/2794678/56832849-53e8cb00-686d-11e9-9565-1a5751bcfc72.png">

<img width="812" alt="Screenshot 2019-04-26 21 50 25" src="https://user-images.githubusercontent.com/2794678/56832862-59deac00-686d-11e9-9a86-5c21e8eb3bee.png">

**Comment by piotrwitek** [comment]
Hey @zaytsevfuu 
I love to receive so detailed reports, thanks ;)
I identified a really tiny bug in recursive conditional type algorithm. I added a new test case to my test suite. Will be released in a few minutes.

Best!

**Comment by zaytsevfuu** [comment]
Hey @piotrwitek, 
thank you for the fast reaction.

It looks like there is still something not working correctly.

Now i am getting this error: `Property 'payload' does not exist on type '{}'.` when trying to access the action payload.

Also it looks like that the original error i described, was gone with `4.1.2`.

I get the payload error with `4.1.2` and `4.1.3`
The payload attribute was working with `4.1.1`.

```
import {ActionType, createReducer, createStandardAction} from "typesafe-actions";

export type State = {
    foo: string,
};

const defaultState: State = {
    foo: "",
};

const actions = {
    foo1: createStandardAction("foo1")<string>(),
    foo2: createStandardAction("foo2")<string>(),
    foo3: createStandardAction("foo3")<string>(),
    foo4: createStandardAction("foo4")(),
};

type FooActionsType = ActionType<typeof actions>;

declare module "typesafe-actions" {
    export type RootAction = FooActionsType;
}

const reducer = createReducer(defaultState)
    .handleAction(actions.foo1, (state, action) => {
        const payload = action.payload;

        return {
            ...state,
        };
    })
    .handleAction(actions.foo2, (state, action) => {
        const payload = action.payload;

        return {
            ...state,
        };
    })
    .handleAction(actions.foo3, (state, action) => {
        const payload = action.payload;

        return {
            ...state,
        };
    })
    .handleAction(actions.foo4, (state, action) => {
        return {
            ...state,
        };
    });

reducer(defaultState, actions.foo1(""));
reducer(defaultState, actions.foo2(""));
reducer(defaultState, actions.foo3(""));
reducer(defaultState, actions.foo4());
```

tsc gives me:

```
reducer.ts:26:32 - error TS2339: Property 'payload' does not exist on type '{}'.

26         const payload = action.payload;
                                  ~~~~~~~

reducer.ts:33:32 - error TS2339: Property 'payload' does not exist on type '{}'.

33         const payload = action.payload;
                                  ~~~~~~~

reducer.ts:40:32 - error TS2339: Property 'payload' does not exist on type '{}'.

40         const payload = action.payload;
                                  ~~~~~~~


Found 3 errors.
```

**Comment by piotrwitek** [comment]
Hey @zaytsevfuu , no problem!

You just need to update the type injection protocol, which was changed to this:
```ts
declare module './type-helpers' {
  interface Types {
    RootAction: ActionType<typeof actions>;
  }
}
```

**Comment by zaytsevfuu** [comment]
That did the trick! Thank you!
