### ISSUE TITLE
typesafe-actions@5.1.0-1: Cannot find module './deprecated'.

### ISSUE THREAD

**Issue by Aridor2006** [piotrwitek/typesafe-actions#205]
## Description
After updating to 5.1.0-1 I get the following error:

/.../node_modules/typesafe-actions/dist/index.d.ts
TypeScript error in /.../node_modules/typesafe-actions/dist/index.d.ts(17,39):
Cannot find module './deprecated'.  TS2307

    15 | export { isActionOf } from './is-action-of';
    16 | export { Types, ActionType, StateType, TypeConstant, Action, Reducer, EmptyAction, PayloadAction, PayloadMetaAction, ActionCreator, EmptyActionCreator, PayloadActionCreator, PayloadMetaActionCreator, ActionCreatorTypeMetadata, ActionBuilder, ActionCreatorBuilder, AsyncActionCreatorBuilder, } from './type-helpers';
  > 17 | export { default as deprecated } from './deprecated';
       |                                       ^
    18 | 

After deleting that line manually everything seems to work after changing my code to the new API.

**Comment by piotrwitek** [comment]
Just released `v5.1.0` with the fix!

**Comment by dregenor** [comment]
Still not work.
node_modules/typesafe-actions/dist/index.d.ts:17:39 - error TS2307: Cannot find module './deprecated'.
